### ISSUE TITLE
getting a low power mode?

### ISSUE THREAD

**Issue by jerabaul29** [adafruit/Adafruit_FRAM_SPI#21]
The datasheet mentions the existence of a low power sleep mode. Any hope that the power modes switching may be added? :)

**Comment by ladyada** [comment]
we have no ETA, please submit a PR!

**Comment by FUEL4EP** [comment]
I' ve added a PR three weeks ago including a low power sleep mode

:-)

**Comment by hathach** [comment]
reviewed, and make some changed since not all chip support sleep mode. We need to check that before sending out command. Also some API rename to be consistent. Please try again to see if still work, thank you for your PR.
