### ISSUE TITLE
Fujitsu FRAM does not appear to support multi-byte sequential writes

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_FRAM_SPI#24]
<img width="889" alt="Screen Shot 2021-07-11 at 02 23 52" src="https://user-images.githubusercontent.com/61756017/125186634-7a4e7300-e1f9-11eb-94b9-1ab640e71568.png">
- Arduino board:  **INSERT ARDUINO BOARD NAME/TYPE HERE**

STM32 Nucleo H743Zi2.

- Arduino IDE version (found in Arduino -> About Arduino menu):  **INSERT ARDUINO
  VERSION HERE**

PlatformIO.

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**

When doing a multi-byte sequential write, some chips (Cypress for example) auto-increment and writes the bytes in order to sequential memory addresses. Fujitsu's chip does not appear to have this functionality, requiring some sort of additional CS signalling to allow increments. Without the special signaling, only the first byte is written.

**Comment by ghost** [comment]
Read has the same issue, and requires special signaling on CS.

**Comment by hathach** [comment]
Can you provide
- simplest sketches modified from stock example that could demonstrate the issue, with comment in comparison to a correct behavior
- Which FRAM chip part you are using
