### ISSUE TITLE
write method const pointer argument

### ISSUE THREAD

**Issue by yilungao** [adafruit/Adafruit_FRAM_SPI#25]
https://github.com/adafruit/Adafruit_FRAM_SPI/blob/44f5b34c8172dafa34a6ab44cb526b7b705552d9/Adafruit_FRAM_SPI.h#L52

Similar to [this issue](https://github.com/adafruit/Adafruit_BusIO/issues/37) it would be nice if the `write` method takes `const uint8_t*` instead of `uint8_t*`. i.e.
changing the method to
`void write(uint32_t addr, const uint8_t *values, size_t count);`

The underlying method `SPIClass::transferBytes` also takes `const uint8_t*`.

I understand this would require changing the code in the Adafruit_BusIO library as well but given [Adafruit_I2CDevice](https://github.com/adafruit/Adafruit_BusIO/blob/master/Adafruit_I2CDevice.h) write() already takes const pointers, it would be nice to be consistent and fix the [Adafruit_SPIDevice](https://github.com/adafruit/Adafruit_BusIO/blob/master/Adafruit_SPIDevice.h) as well.

Can submit a PR if that works.

**Comment by hathach** [comment]
yup, please submit PR, I will help with reviewing if there is any issue.

**Comment by zencow** [comment]
The update to Adafruit_BusIO  broke my project.  It doesn't compile.  I submitted an Issue.
