### ISSUE TITLE
Adafruit_FRAM_SPI rel.2.4.1 error: invalid conversion from 'const uint8_t*' to 'uint8_t*'

### ISSUE THREAD

**Issue by pippo-75** [adafruit/Adafruit_FRAM_SPI#27]
Hi all, using Arduino IDE 1.8.20 (NOT relevant) on Win10 (NOT relevant), selecting ESP32,
Tools setting ==> Primary Debug Level: "Verbose", using this code (just the minimum to reproduce the problem):

// Adafruit_FRAM_SPI library version 2.4.1
#include <Adafruit_FRAM_SPI.h>

// instantiate the SPI library defining the used SPI pins
// HSPI ==> SCLK=14, MISO=12, MOSI=13, CS=15)
Adafruit_FRAM_SPI myFRAM = Adafruit_FRAM_SPI(14, 12, 13, 15);

void setup() {
  // put your setup code here, to run once:
  myFRAM.begin();
  //
}

void loop() {
  // put your main code here, to run repeatedly:
}

On Serial Monitor I am notified:
Adafruit_FRAM_SPI.cpp:220:18: error: invalid conversion from 'const uint8_t*' {aka 'const unsigned char*'} to 'uint8_t*' {aka 'unsigned char*'} [-fpermissive]
Adafruit_SPIDevice.h:80:23: note:   initializing argument 1 of 'bool Adafruit_SPIDevice::write(uint8_t*, size_t, uint8_t*, size_t)'

Obviously, after removing that -const- from the two files, the whole thing is compiled without errors / warnings.

**Comment by pippo-75** [comment]
Just to clarify: the version 2.4.0 of the library does not report any type of error/warning.

**Comment by hathach** [comment]
which library version of `Adafruit BusIO` that you have, if it is not latest (as of now 1.11.6), then update it and try again.

**Comment by pippo-75** [comment]
Yes, you are right - I was using 1.11.1 and after the update the error disappeared.
I didn't imagine having to update them together. 
Thanks for the 'news' and have a nice day.

**Comment by hathach** [comment]
Thanks for your confirmation. Closed now.
