### ISSUE TITLE
Address range.

### ISSUE THREAD

**Issue by pholmes2012** [adafruit/Adafruit_FRAM_SPI#5]
I have modified an Adafruit FRAM SPI breakout board to use a 4Mbit FRAM chip and found two issues with this driver.

1. The default maunufacture ID is 0x7f and default product ID is 0x7f7f so fails obviously.

2. The read and write functions take only a 16bit address, 24bit addresses are required for > 64K chips. 

I have modified this driver locally and everything works up to the full 512K.

I realise you are probably not interested in supporting modified boards, which covers point 1, but will you be addressing point 2 in the near future?

**Comment by ladyada** [comment]
hiya if you can make sure it still works with an original SPI FRAM board we'd take a PR for both!

**Comment by pholmes2012** [comment]
It does, I added a default parameter to begin() specifying the address byte
width, therefore all existing sketches will default to 2 bytes.

One thing that bothers me slightly is that the new chips' datasheet
mentions that the top 4 or 5 bits of the 24bit address are used for
something, I have not read it in depth yet. Basically that may mean the
default parameter should be an address bit width rather than byte width. I
will look into that.

Ok I will look at doing a PR this weekend.

Paul.

**Comment by deanm1278** [comment]
ok PR has been checked and merged. Thanks for the contribution!
