### ISSUE TITLE
Compilation error on SAMD51 boards related to SPI clock divider

### ISSUE THREAD

**Issue by XFactHD** [adafruit/Adafruit_FRAM_SPI#8]
- Arduino board:  Adafruit (ItsyBitsy/Feather/Metro/Trellis) M4

- Arduino IDE version:  Arduino IDE 1.8.5

- Steps to reproduce the problem:

```
#include <Adafruit_FRAM_SPI.h>
void setup() {}
void loop() {}
```

Compiling these three lines for any SAMD51 based board from Adafruit causes a compilation error in the  begin() function on [line 97](https://github.com/adafruit/Adafruit_FRAM_SPI/blob/ad64b3ca970e049547ccc8b7e517c79fce805745/Adafruit_FRAM_SPI.cpp#L71) where the clock divider is set.
Looking at the error
```
Adafruit_FRAM_SPI.cpp:97:23: error: SPI_CLOCK_DIV2 was not declared in this scope
SPI.setClockDivider (SPI_CLOCK_DIV2); // 8 MHz
```

leads me to believe that the SAMD51 boards are completely missing the SPI clock divider defines.

If you would prefer to handle this issue over on your Arduino_SAMD repo, I will move it there.

**Comment by ladyada** [comment]
oh yeah this is ancient, and should be redone to use SPI transactions. would you be interested in replacing the current code to use transactions and submitting a PR?

**Comment by XFactHD** [comment]
Sure, I'll take a look and submit a PR when I get it working.

**Comment by ladyada** [comment]
sweet, thanks!

**Comment by XFactHD** [comment]
I have opened a PR with the requested changes.

**Comment by ladyada** [comment]
resolved!
